function y = doFilter(x)
%DOFILTER 입력값 x를 필터링하여 출력값 y를 반환합니다.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 11-Aug-2022 12:34:11

persistent Hd;

if isempty(Hd)
    
    N  = 20;    % Order
    F0 = 0.5;  % Center frequency
    BW = 0.1;  % Bandwidth
    
    h = fdesign.notch('N,F0,BW', N, F0, BW);
    
    Hd = design(h, 'butter', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

