
classdef gnssPVT < ros.Message
    %gnssPVT MATLAB implementation of ublox_f9r/gnssPVT
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ublox_f9r/gnssPVT' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '76a709426465468a80d5b09ed58df78d' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'ITOW' 'Year' 'Month' 'Day' 'Hour' 'Min' 'Sec' 'Valid' 'TAcc' 'Nano' 'FixType' 'Flags' 'Flags2' 'NumSV' 'Lon' 'Lat' 'Height' 'HMSL' 'HAcc' 'VAcc' 'VelN' 'VelE' 'VelD' 'GSpeed' 'Heading' 'SAcc' 'HeadAcc' 'PDOP' 'Reserved1' 'HeadVeh' 'MagDec' 'MagAcc' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'iTOW' 'year' 'month' 'day' 'hour' 'min' 'sec' 'valid' 'tAcc' 'nano' 'fixType' 'flags' 'flags2' 'numSV' 'lon' 'lat' 'height' 'hMSL' 'hAcc' 'vAcc' 'velN' 'velE' 'velD' 'gSpeed' 'heading' 'sAcc' 'headAcc' 'pDOP' 'reserved1' 'headVeh' 'magDec' 'magAcc' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        CLASSID = uint8(1)
        MESSAGEID = uint8(7)
        VALIDDATE = uint8(1)
        VALIDTIME = uint8(2)
        VALIDFULLYRESOLVED = uint8(4)
        VALIDMAG = uint8(8)
        FIXTYPENOFIX = uint8(0)
        FIXTYPEDEADRECKONINGONLY = uint8(1)
        FIXTYPE2D = uint8(2)
        FIXTYPE3D = uint8(3)
        FIXTYPEGNSSDEADRECKONINGCOMBINED = uint8(4)
        FIXTYPETIMEONLY = uint8(5)
        FLAGSGNSSFIXOK = uint8(1)
        FLAGSDIFFSOLN = uint8(2)
        FLAGSPSMMASK = uint8(28)
        PSMOFF = uint8(0)
        PSMENABLED = uint8(4)
        PSMACQUIRED = uint8(8)
        PSMTRACKING = uint8(12)
        PSMPOWEROPTIMIZEDTRACKING = uint8(16)
        PSMINACTIVE = uint8(20)
        FLAGSHEADVEHVALID = uint8(32)
        FLAGSCARRIERPHASEMASK = uint8(192)
        CARRIERPHASENOSOLUTION = uint8(0)
        CARRIERPHASEFLOAT = uint8(64)
        CARRIERPHASEFIXED = uint8(128)
        FLAGS2CONFIRMEDAVAILABLE = uint8(32)
        FLAGS2CONFIRMEDDATE = uint8(64)
        FLAGS2CONFIRMEDTIME = uint8(128)
    end
    properties
        Header
        ITOW
        Year
        Month
        Day
        Hour
        Min
        Sec
        Valid
        TAcc
        Nano
        FixType
        Flags
        Flags2
        NumSV
        Lon
        Lat
        Height
        HMSL
        HAcc
        VAcc
        VelN
        VelE
        VelD
        GSpeed
        Heading
        SAcc
        HeadAcc
        PDOP
        Reserved1
        HeadVeh
        MagDec
        MagAcc
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'Header')
            obj.Header = val;
        end
        function set.ITOW(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'ITOW');
            obj.ITOW = uint32(val);
        end
        function set.Year(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'Year');
            obj.Year = uint16(val);
        end
        function set.Month(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'Month');
            obj.Month = uint8(val);
        end
        function set.Day(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'Day');
            obj.Day = uint8(val);
        end
        function set.Hour(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'Hour');
            obj.Hour = uint8(val);
        end
        function set.Min(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'Min');
            obj.Min = uint8(val);
        end
        function set.Sec(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'Sec');
            obj.Sec = uint8(val);
        end
        function set.Valid(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'Valid');
            obj.Valid = uint8(val);
        end
        function set.TAcc(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'TAcc');
            obj.TAcc = uint32(val);
        end
        function set.Nano(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'Nano');
            obj.Nano = int32(val);
        end
        function set.FixType(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'FixType');
            obj.FixType = uint8(val);
        end
        function set.Flags(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'Flags');
            obj.Flags = uint8(val);
        end
        function set.Flags2(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'Flags2');
            obj.Flags2 = uint8(val);
        end
        function set.NumSV(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'NumSV');
            obj.NumSV = uint8(val);
        end
        function set.Lon(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'Lon');
            obj.Lon = int32(val);
        end
        function set.Lat(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'Lat');
            obj.Lat = int32(val);
        end
        function set.Height(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'Height');
            obj.Height = int32(val);
        end
        function set.HMSL(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'HMSL');
            obj.HMSL = int32(val);
        end
        function set.HAcc(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'HAcc');
            obj.HAcc = uint32(val);
        end
        function set.VAcc(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'VAcc');
            obj.VAcc = uint32(val);
        end
        function set.VelN(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'VelN');
            obj.VelN = int32(val);
        end
        function set.VelE(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'VelE');
            obj.VelE = int32(val);
        end
        function set.VelD(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'VelD');
            obj.VelD = int32(val);
        end
        function set.GSpeed(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'GSpeed');
            obj.GSpeed = int32(val);
        end
        function set.Heading(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'Heading');
            obj.Heading = int32(val);
        end
        function set.SAcc(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'SAcc');
            obj.SAcc = uint32(val);
        end
        function set.HeadAcc(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'HeadAcc');
            obj.HeadAcc = uint32(val);
        end
        function set.PDOP(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'PDOP');
            obj.PDOP = uint16(val);
        end
        function set.Reserved1(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 6};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'Reserved1');
            obj.Reserved1 = uint8(val);
        end
        function set.HeadVeh(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'HeadVeh');
            obj.HeadVeh = int32(val);
        end
        function set.MagDec(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'MagDec');
            obj.MagDec = int16(val);
        end
        function set.MagAcc(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'gnssPVT', 'MagAcc');
            obj.MagAcc = uint16(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ublox_f9r.gnssPVT.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ublox_f9r.gnssPVT(strObj);
        end
    end
end
