// Generated by gencpp from file localizer_zed_f9r/Acc.msg
// DO NOT EDIT!


#ifndef LOCALIZER_ZED_F9R_MESSAGE_ACC_H
#define LOCALIZER_ZED_F9R_MESSAGE_ACC_H

#include <ros/service_traits.h>


#include <localizer_zed_f9r/AccRequest.h>
#include <localizer_zed_f9r/AccResponse.h>


namespace localizer_zed_f9r
{

struct Acc
{

typedef AccRequest Request;
typedef AccResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Acc
} // namespace localizer_zed_f9r


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::localizer_zed_f9r::Acc > {
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::localizer_zed_f9r::Acc&) { return value(); }
};

template<>
struct DataType< ::localizer_zed_f9r::Acc > {
  static const char* value()
  {
    return "localizer_zed_f9r/Acc";
  }

  static const char* value(const ::localizer_zed_f9r::Acc&) { return value(); }
};


// service_traits::MD5Sum< ::localizer_zed_f9r::AccRequest> should match
// service_traits::MD5Sum< ::localizer_zed_f9r::Acc >
template<>
struct MD5Sum< ::localizer_zed_f9r::AccRequest>
{
  static const char* value()
  {
    return MD5Sum< ::localizer_zed_f9r::Acc >::value();
  }
  static const char* value(const ::localizer_zed_f9r::AccRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::localizer_zed_f9r::AccRequest> should match
// service_traits::DataType< ::localizer_zed_f9r::Acc >
template<>
struct DataType< ::localizer_zed_f9r::AccRequest>
{
  static const char* value()
  {
    return DataType< ::localizer_zed_f9r::Acc >::value();
  }
  static const char* value(const ::localizer_zed_f9r::AccRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::localizer_zed_f9r::AccResponse> should match
// service_traits::MD5Sum< ::localizer_zed_f9r::Acc >
template<>
struct MD5Sum< ::localizer_zed_f9r::AccResponse>
{
  static const char* value()
  {
    return MD5Sum< ::localizer_zed_f9r::Acc >::value();
  }
  static const char* value(const ::localizer_zed_f9r::AccResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::localizer_zed_f9r::AccResponse> should match
// service_traits::DataType< ::localizer_zed_f9r::Acc >
template<>
struct DataType< ::localizer_zed_f9r::AccResponse>
{
  static const char* value()
  {
    return DataType< ::localizer_zed_f9r::Acc >::value();
  }
  static const char* value(const ::localizer_zed_f9r::AccResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCALIZER_ZED_F9R_MESSAGE_ACC_H
