// Generated by gencpp from file localizer_zed_f9r/AccRequest.msg
// DO NOT EDIT!


#ifndef LOCALIZER_ZED_F9R_MESSAGE_ACCREQUEST_H
#define LOCALIZER_ZED_F9R_MESSAGE_ACCREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace localizer_zed_f9r
{
template <class ContainerAllocator>
struct AccRequest_
{
  typedef AccRequest_<ContainerAllocator> Type;

  AccRequest_()
    {
    }
  AccRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::localizer_zed_f9r::AccRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localizer_zed_f9r::AccRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AccRequest_

typedef ::localizer_zed_f9r::AccRequest_<std::allocator<void> > AccRequest;

typedef boost::shared_ptr< ::localizer_zed_f9r::AccRequest > AccRequestPtr;
typedef boost::shared_ptr< ::localizer_zed_f9r::AccRequest const> AccRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localizer_zed_f9r::AccRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localizer_zed_f9r::AccRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace localizer_zed_f9r

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::localizer_zed_f9r::AccRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localizer_zed_f9r::AccRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localizer_zed_f9r::AccRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localizer_zed_f9r::AccRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localizer_zed_f9r::AccRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localizer_zed_f9r::AccRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localizer_zed_f9r::AccRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::localizer_zed_f9r::AccRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::localizer_zed_f9r::AccRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localizer_zed_f9r/AccRequest";
  }

  static const char* value(const ::localizer_zed_f9r::AccRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localizer_zed_f9r::AccRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::localizer_zed_f9r::AccRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localizer_zed_f9r::AccRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AccRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localizer_zed_f9r::AccRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::localizer_zed_f9r::AccRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZER_ZED_F9R_MESSAGE_ACCREQUEST_H
