// Generated by gencpp from file localizer_zed_f9r/Gyro.msg
// DO NOT EDIT!


#ifndef LOCALIZER_ZED_F9R_MESSAGE_GYRO_H
#define LOCALIZER_ZED_F9R_MESSAGE_GYRO_H

#include <ros/service_traits.h>


#include <localizer_zed_f9r/GyroRequest.h>
#include <localizer_zed_f9r/GyroResponse.h>


namespace localizer_zed_f9r
{

struct Gyro
{

typedef GyroRequest Request;
typedef GyroResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Gyro
} // namespace localizer_zed_f9r


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::localizer_zed_f9r::Gyro > {
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::localizer_zed_f9r::Gyro&) { return value(); }
};

template<>
struct DataType< ::localizer_zed_f9r::Gyro > {
  static const char* value()
  {
    return "localizer_zed_f9r/Gyro";
  }

  static const char* value(const ::localizer_zed_f9r::Gyro&) { return value(); }
};


// service_traits::MD5Sum< ::localizer_zed_f9r::GyroRequest> should match
// service_traits::MD5Sum< ::localizer_zed_f9r::Gyro >
template<>
struct MD5Sum< ::localizer_zed_f9r::GyroRequest>
{
  static const char* value()
  {
    return MD5Sum< ::localizer_zed_f9r::Gyro >::value();
  }
  static const char* value(const ::localizer_zed_f9r::GyroRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::localizer_zed_f9r::GyroRequest> should match
// service_traits::DataType< ::localizer_zed_f9r::Gyro >
template<>
struct DataType< ::localizer_zed_f9r::GyroRequest>
{
  static const char* value()
  {
    return DataType< ::localizer_zed_f9r::Gyro >::value();
  }
  static const char* value(const ::localizer_zed_f9r::GyroRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::localizer_zed_f9r::GyroResponse> should match
// service_traits::MD5Sum< ::localizer_zed_f9r::Gyro >
template<>
struct MD5Sum< ::localizer_zed_f9r::GyroResponse>
{
  static const char* value()
  {
    return MD5Sum< ::localizer_zed_f9r::Gyro >::value();
  }
  static const char* value(const ::localizer_zed_f9r::GyroResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::localizer_zed_f9r::GyroResponse> should match
// service_traits::DataType< ::localizer_zed_f9r::Gyro >
template<>
struct DataType< ::localizer_zed_f9r::GyroResponse>
{
  static const char* value()
  {
    return DataType< ::localizer_zed_f9r::Gyro >::value();
  }
  static const char* value(const ::localizer_zed_f9r::GyroResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCALIZER_ZED_F9R_MESSAGE_GYRO_H
