%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.14 and Fixed-Point Designer 7.6           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [cent_pos_est,cent_vel_est,kf_psi,gyro_psi,b_acc_o,b_gyro,state_o,acc_b_phi,acc_b_theta] = IMUpos_wrapper_fixpt(IMUacc_c,IMUgyro_c,s_time,b_acc_o,b_gyro,mode,kf_psi,gyro_psi,cent_pos_est,cent_vel_est)
    fm = get_fimath();
    IMUacc_c_in = fi( IMUacc_c, 1, 16, 11, fm );
    IMUgyro_c_in = fi( IMUgyro_c, 1, 16, 15, fm );
    s_time_in = fi( s_time, 0, 16, -15, fm );
    b_acc_o_in = fi( b_acc_o, 1, 16, 15, fm );
    b_gyro_in = fi( b_gyro, 1, 16, 23, fm );
    mode_in = fi( mode, 0, 1, 0, fm );
    kf_psi_in = fi( kf_psi, 1, 16, 13, fm );
    gyro_psi_in = fi( gyro_psi, 1, 16, 13, fm );
    cent_pos_est_in = fi( cent_pos_est, 1, 16, 10, fm );
    cent_vel_est_in = fi( cent_vel_est, 1, 16, 13, fm );
    [cent_pos_est_out,cent_vel_est_out,kf_psi_out,gyro_psi_out,b_acc_o_out,b_gyro_out,state_o_out,acc_b_phi_out,acc_b_theta_out] = IMUpos_fixpt( IMUacc_c_in, IMUgyro_c_in, s_time_in, b_acc_o_in, b_gyro_in, mode_in, kf_psi_in, gyro_psi_in, cent_pos_est_in, cent_vel_est_in );
    cent_pos_est = double( cent_pos_est_out );
    cent_vel_est = double( cent_vel_est_out );
    kf_psi = double( kf_psi_out );
    gyro_psi = double( gyro_psi_out );
    b_acc_o = double( b_acc_o_out );
    b_gyro = double( b_gyro_out );
    state_o = double( state_o_out );
    acc_b_phi = double( acc_b_phi_out );
    acc_b_theta = double( acc_b_theta_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
