%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.14 and Fixed-Point Designer 7.6           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [cent_pos_est, cent_vel_est, kf_psi, gyro_psi, b_acc_o, b_gyro, state_o, acc_b_phi,acc_b_theta] = IMUpos_fixpt(IMUacc_c, IMUgyro_c, s_time, b_acc_o_1, b_gyro_1, mode, kf_psi_1, gyro_psi_1, cent_pos_est_1, cent_vel_est_1)


%% mode : 0 -> F9R,  1 -> Xens
fm = get_fimath();
b_acc_o = fi(b_acc_o_1, 1, 16, 15, fm);
b_gyro = fi(b_gyro_1, 1, 16, 23, fm);
cent_pos_est = fi(cent_pos_est_1, 1, 16, 10, fm);
cent_vel_est = fi(cent_vel_est_1, 1, 16, 13, fm);
gyro_psi = fi(gyro_psi_1, 1, 16, 13, fm);
kf_psi = fi(kf_psi_1, 1, 16, 13, fm);

if mode == fi(1, 0, 1, 0, fm)
dt_acc = fi(0.01, 0, 16, 22, fm);
dt_gyro = fi(0.01, 0, 16, 22, fm);
else
%F2F: No information found for converting the following block of code
%F2F: Start block
dt_acc = fi(0.01, 0, 16, 22, fm);
dt_gyro = fi(0.03, 0, 16, 22, fm);
%F2F: End block
end    
Lv = fi(10, 0, 4, 0, fm);
persistent k IMUacc IMUgyro s_time_prev Acc_Acc Acc_Vel Acc_Pos gyro_theta state gyro_phi % Acc_Steady Acc_PQR Acc_Acc_a kf_phi kf_theta %gyro_psi 
gravity = fi(9.8, 0, 16, 12, fm);

if isempty (k)
    k = fi(0, 0, 10, 0, fm);
    state = fi(0, 0, 2, 0, fm); % 0 : init,
    IMUacc = fi(zeros(fi_toint(fi(2, 0, 2, 0, fm)*Lv), 3), 1, 16, 11, fm);
    IMUgyro = fi(zeros(fi_toint(fi(2, 0, 2, 0, fm)*Lv), 3), 1, 16, 15, fm);
    Acc_Acc = fi(zeros(3,fi_toint(fi(2, 0, 2, 0, fm)*Lv) ), 1, 16, 13, fm);
    Acc_Vel = fi(zeros(3,fi_toint(fi(2, 0, 2, 0, fm)*Lv)), 1, 16, 13, fm);
    Acc_Pos = fi(zeros(3,fi_toint(fi(2, 0, 2, 0, fm)*Lv)), 1, 16, 10, fm);
    
%%%%% For Test %%%%%%
%     Acc_Steady = zeros(3,2*Lv);
%     Acc_PQR = zeros(3,2*Lv);
%     Acc_Acc_a = zeros(3,2*Lv );
%     kf_phi = 0;
%     kf_theta = 0;
%%%%%%%%%%%%%%%%%%%%%%%

    gyro_phi = fi(0, 1, 16, 17, fm);
    gyro_theta = fi(0, 1, 16, 17, fm);


%     gyro_psi = 0;
end

if k < fi(900, 0, 10, 0, fm)
    k(:) = k + fi(1, 0, 1, 0, fm);
end

IMUgyro(1:end-1, :) = IMUgyro(2:end, :);
IMUgyro(end,:)  = IMUgyro_c;
IMUacc(1:end-1, :) = IMUacc(2:end, :);
IMUacc(end,:) = IMUacc_c;

Acc_Vel(:,end) = cent_vel_est;
Acc_Pos(:,end) = cent_pos_est;

% dt_gyro = s_time - s_time_prev;

if k > fi(100, 0, 7, 0, fm)
    state(:) = 2;
    if mode == fi(1, 0, 1, 0, fm)
        p = fi((fi_signed(IMUgyro(end,1))-b_gyro(1)), 1, 16, 17, fm);    q = fi((fi_signed(IMUgyro(end,2))-b_gyro(2)), 1, 16, 17, fm);    r = fi((fi_signed(IMUgyro(end,3))-b_gyro(3)), 1, 16, 15, fm);
    else
        %F2F: No information found for converting the following block of code
        %F2F: Start block
        p = fi((fi_signed(IMUgyro(end,1))-b_gyro(1))*fi(pi, 0, 16, 14, fm)*fi(1/180, 0, 16, 23, fm), 1, 16, 17, fm);    q = fi((fi_signed(IMUgyro(end,2))-b_gyro(2))*fi(pi, 0, 16, 14, fm)*fi(1/180, 0, 16, 23, fm), 1, 16, 17, fm);    r = fi((fi_signed(IMUgyro(end,3))-b_gyro(3))*fi(pi, 0, 16, 14, fm)*fi(1/180, 0, 16, 23, fm), 1, 16, 15, fm);
%F2F: End block

    end

    acc_b = fi((IMUacc(end,[1 2 3])-b_acc_o)', 1, 16, 11, fm);

    used_phi = fi(0, 0, 1, 0, fm);
    used_theta = fi(0, 0, 1, 0, fm);
    used_psi = fi(kf_psi, 1, 16, 13, fm);

    %%% for test
%     used_phi = kf_phi;
%     used_theta = kf_theta;
%     used_psi = kf_psi;

    
    used_phi_next = fi(0, 0, 1, 0, fm);
    used_theta_next = fi(0, 0, 1, 0, fm);
    used_psi_next = fi(kf_psi, 1, 16, 13, fm);

    Acc_Pos(:,end) = cent_pos_est;
    Acc_Vel(:,end) = cent_vel_est;
    Acc_Pos(:,1:end-1) = Acc_Pos(:,2:end);
    Acc_Vel(:,1:end-1) = Acc_Vel(:,2:end);
    Acc_Acc(:,1:end-1) = Acc_Acc(:,2:end);
    %%%%%%%%%%%%%%%%% For Test %%%%%%%%%%%%%%%%%%
%     Acc_Acc_a(:,1:end-1) = Acc_Acc_a(:,2:end);
%     Acc_PQR(:,1:end-1) = Acc_PQR(:,2:end);
%     Acc_Steady(:,1:end-1) = Acc_Steady(:,2:end);
% 
%             %         vel_t = rotationVectorToMatrix([used_phi;used_theta;used_psi])*Acc_Vel(:,i-1);
%             %         Acc_PQR(:,i) = 1*([0 vel_t(3) -vel_t(2);-vel_t(3) 0 0;vel_t(2) 0 0]*[p;q;r]);
%             %         Acc_Steady(:,i) = gravity*[sin(used_theta_next);-cos(used_theta_next)*sin(used_phi_next);-cos(used_theta_next)*cos(used_phi_next)];
%             %         Acc_Acc(:,i) = rotationVectorToMatrix([used_phi;used_theta;used_psi])'*(acc_b(:,i)-Acc_PQR(:,i)-Acc_Steady(:,i));
%             vel_t = [0 1 0;1 0 0;0 0 1]*rotationVectorToMatrix([used_phi;used_theta;used_psi])*Acc_Vel(:,end-1);
%             Acc_PQR(:,end) = [0 1 0;1 0 0;0 0 1]*([0 vel_t(3) -vel_t(2);-vel_t(3) 0 0;vel_t(2) 0 0]*[p;q;r]);
% %             Acc_PQR(:,end) = [0;0;0];
%             Acc_Steady(:,end) = [0 1 0;1 0 0;0 0 1]*gravity*[sin(used_theta);-cos(used_theta)*sin(used_phi);-cos(used_theta)*cos(used_phi)];
%             Acc_Acc_a(:,end) = [0 1 0;1 0 0;0 0 1]*rotationVectorToMatrix([used_phi;used_theta;used_psi])'*(acc_b-Acc_PQR(:,end)-Acc_Steady(:,end));
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    %if mode == 1
        Acc_Acc(:,end) = fi([0 1 0;1 0 0;0 0 1], 0, 1, 0, fm)*rotationVectorToMatrix([fi(0, 1, 16, 13, fm);fi(0, 0, 1, 0, fm);used_psi])'*([fi(acc_b(1), 1, 16, 11, fm);acc_b(2);fi(0, 0, 1, 0, fm)]);
%     else
%         Acc_Acc(:,end) = [0 1 0;1 0 0;0 0 1]*rotationVectorToMatrix([0;0;used_psi])'*([acc_b(1);acc_b(2);0]);
%     end

    [gyro_phi(:),gyro_theta(:),fmo_1] = EulerGyroUpdate(p,q,r,dt_gyro,gyro_phi,gyro_theta,gyro_psi);
    gyro_psi = fi(fmo_1, 1, 16, 13, fm);
%     [gyro_phi,gyro_theta,gyro_psi] = EulerGyroUpdate(p,q,r,dt_acc,gyro_phi,gyro_theta,gyro_psi);

    [fmo_2,fmo_3] = EulerAcc(acc_b(1), acc_b(2), acc_b(3));
    acc_b_phi = fi(fmo_2, 1, 16, 16, fm);
    acc_b_theta = fi(fmo_3, 1, 16, 16, fm);

    qua_acc = fi(EulerToQuaternion(acc_b_phi, acc_b_theta, gyro_psi), 1, 16, 15, fm);
    qua_kf = fi(EulerToQuaternion(gyro_phi,gyro_theta,gyro_psi), 1, 16, 15, fm);
    AA = fi(fi(eye(4), 0, 1, 0, fm)+fi_div_by_shift(dt_gyro*fi(1, 0, 1, 0, fm), 1)*[fi(0, 1, 16, 15, fm) fi_uminus(p) fi_uminus(q) fi_uminus(r);    fi(p, 1, 16, 15, fm) 0 r fi_uminus(q);    fi(q, 1, 16, 15, fm) fi_uminus(r) 0 p;    fi(r, 1, 16, 15, fm) q fi_uminus(p) 0    ], 1, 16, 14, fm);
    % %
    [fmo_4,fmo_5,fmo_6] = EulerKalman_2(qua_kf,AA,qua_acc);
    kf_phi = fi(fmo_4, 1, 16, 17, fm);
    kf_theta = fi(fmo_5, 1, 16, 17, fm);
    kf_psi = fi(fmo_6, 1, 16, 13, fm);
    kf_phi(:) =real(kf_phi);
    kf_theta(:) =real(kf_theta);
    kf_psi(:) =real(kf_psi);

    Acc_Vel(:,end) = Acc_Vel(:,end-1) + Acc_Acc(:,end)*dt_acc;
    Acc_Pos(:,end) = Acc_Pos(:,end-1) + Acc_Vel(:,end-1)*dt_acc + fi_div_by_shift(Acc_Acc(:,end)*dt_acc^2, 1);

elseif k == fi(100, 0, 7, 0, fm)

    b_gyro = fi(mean(IMUgyro), 1, 16, 23, fm);
    b_acc_o = fi((mean(IMUacc)'+[fi(0, 0, 16, 12, fm);fi(0, 0, 1, 0, fm);gravity])', 1, 16, 15, fm);
    if mode == fi(1, 0, 1, 0, fm)
        p = fi((fi_signed(IMUgyro(end,1))-b_gyro(1)), 1, 16, 17, fm);    q = fi((IMUgyro(end,2)-b_gyro(2)), 1, 16, 17, fm);    r = fi((IMUgyro(end,3)-b_gyro(3)), 1, 16, 15, fm);
    else
        %F2F: No information found for converting the following block of code
        %F2F: Start block
        p = fi((fi_signed(IMUgyro(end,1))-b_gyro(1))*fi(pi, 0, 16, 14, fm)*fi(1/180, 0, 16, 23, fm), 1, 16, 17, fm);    q = fi((fi_signed(IMUgyro(end,2))-b_gyro(2))*fi(pi, 0, 16, 14, fm)*fi(1/180, 0, 16, 23, fm), 1, 16, 17, fm);    r = fi((fi_signed(IMUgyro(end,3))-b_gyro(3))*fi(pi, 0, 16, 14, fm)*fi(1/180, 0, 16, 23, fm), 1, 16, 15, fm);
%F2F: End block

    end
    acc_b = fi((IMUacc(end,:)-b_acc_o)', 1, 16, 11, fm);

    [fmo_7,fmo_8] = EulerAcc(acc_b(1), acc_b(2), acc_b(3));
    acc_b_phi = fi(fmo_7, 1, 16, 16, fm);
    acc_b_theta = fi(fmo_8, 1, 16, 16, fm);
    gyro_phi(:) = acc_b_phi;
    kf_phi = fi(gyro_phi, 1, 16, 17, fm);
    gyro_theta(:) = acc_b_theta;
    kf_theta = fi(gyro_theta, 1, 16, 17, fm);
    gyro_psi = fi(kf_psi, 1, 16, 13, fm);
    state(:) = 1;
else
    if mode == fi(1, 0, 1, 0, fm)
        p = fi((IMUgyro(end,1)), 1, 16, 17, fm);    q = fi((IMUgyro(end,2)), 1, 16, 17, fm);    r = fi((IMUgyro(end,3)), 1, 16, 15, fm);
    else
        %F2F: No information found for converting the following block of code
        %F2F: Start block
        p = fi((IMUgyro(end,1))*fi(pi, 0, 16, 14, fm)*fi(1/180, 0, 16, 23, fm), 1, 16, 17, fm);    q = fi((IMUgyro(end,2))*fi(pi, 0, 16, 14, fm)*fi(1/180, 0, 16, 23, fm), 1, 16, 17, fm);    r = fi((IMUgyro(end,3))*fi(pi, 0, 16, 14, fm)*fi(1/180, 0, 16, 23, fm), 1, 16, 15, fm);
%F2F: End block

    end
    acc_b = fi((IMUacc(end,:))', 1, 16, 11, fm);

    Acc_Vel(:,1:end-1) = Acc_Vel(:,2:end);
    Acc_Acc(:,1:end-1) = Acc_Acc(:,2:end);
    Acc_Pos(:,1:end-1) = Acc_Pos(:,2:end);

    Acc_Acc(:,end) = [0 0 0]';
    Acc_Vel(:,end) = [fi(cent_vel_est(1), 1, 16, 13, fm) cent_vel_est(2) cent_vel_est(3)]';
    Acc_Pos(:,end) = [fi(cent_pos_est(1), 1, 16, 10, fm) cent_pos_est(2) cent_pos_est(3)]';

    [fmo_9,fmo_10] = EulerAcc(acc_b(1), acc_b(2), acc_b(3));
    acc_b_phi = fi(fmo_9, 1, 16, 16, fm);
    acc_b_theta = fi(fmo_10, 1, 16, 16, fm);
    gyro_phi(:) = fi_div(gyro_phi*(k-fi(1, 0, 1, 0, fm)), k)+fi_div(acc_b_phi, k);
    kf_phi = fi(gyro_phi, 1, 16, 17, fm);
    gyro_theta(:) = fi_div(gyro_theta*(k-fi(1, 0, 1, 0, fm)), k)+fi_div(acc_b_theta, k);
    kf_theta = fi(gyro_theta, 1, 16, 17, fm);
    gyro_psi = fi(kf_psi, 1, 16, 13, fm);
    %             b_gyro = b_gyro*(k0(5)-1)/k0(5)+IMUgyro(end,:)/k0(5);
end

s_time_prev = fi(s_time, 0, 16, -15, fm);
cent_pos_est = fi(Acc_Pos(:,end), 1, 16, 10, fm);
cent_vel_est = fi(Acc_Vel(:,end), 1, 16, 13, fm);
state_o = fi(state, 0, 2, 0, fm);
end

function [phi, theta, psi] = EulerGyroUpdate(p,q,r,dt,phi_p, theta_p, psi_p)

fm = get_fimath();

UpdateMat = fi([fi(1, 1, 16, 14, fm) sin(phi_p)*tan(theta_p) cos(phi_p)*tan(theta_p);fi(0, 1, 16, 14, fm) cos(phi_p) fi_uminus(sin(phi_p));fi(0, 1, 16, 14, fm) fi_div(sin(phi_p), cos(theta_p)) fi_div(cos(phi_p), cos(theta_p))], 1, 16, 14, fm);

NextEuler = fi([fi(phi_p, 1, 16, 13, fm);theta_p;psi_p] + dt*UpdateMat*[fi(p, 1, 16, 15, fm);q;r], 1, 16, 13, fm);

phi = fi(NextEuler(1), 1, 16, 17, fm);
theta = fi(NextEuler(2), 1, 16, 17, fm);
psi = fi(NextEuler(3), 1, 16, 13, fm);
end

function [phi, theta] = EulerAcc(ax, ay, az)

fm = get_fimath();

phi = fi(atan(fi_div(ay, az)), 1, 16, 16, fm);
theta = fi(atan(fi_div(ax, sqrt(ay^2 + az^2))), 1, 16, 16, fm);
end

function z = EulerToQuaternion(phi, theta, psi)

fm = get_fimath();

sinPhi      = fi(sin(fi_div_by_shift(phi, 1)), 1, 16, 17, fm);   cosPhi = fi(cos(fi_div_by_shift(phi, 1)), 0, 16, 15, fm);
sinTheta    = fi(sin(fi_div_by_shift(theta, 1)), 1, 16, 17, fm); cosTheta = fi(cos(fi_div_by_shift(theta, 1)), 0, 16, 15, fm);
sinPsi      = fi(sin(fi_div_by_shift(psi, 1)), 1, 16, 14, fm); cosPsi = fi(cos(fi_div_by_shift(psi, 1)), 1, 16, 14, fm);

z = fi([ fi(cosPhi*cosTheta*cosPsi  + sinPhi*sinTheta*sinPsi, 1, 16, 15, fm);
      fi_signed(sinPhi*cosTheta*cosPsi)  - cosPhi*sinTheta*sinPsi;
      cosPhi*sinTheta*cosPsi  + sinPhi*cosTheta*sinPsi;
      fi_signed(cosPhi*cosTheta*sinPsi)  - sinPhi*sinTheta*cosPsi;
      ], 1, 16, 15, fm);
end

function [phi,theta,psi] = EulerKalman_2(x_1,A,z)

fm = get_fimath();
x = fi(x_1, 1, 16, 15, fm);

persistent H Q R
persistent P
persistent firstRun

if isempty(firstRun)
    H = fi(eye(4), 0, 1, 0, fm);
    
    Q = fi(1e0*eye(4), 0, 1, 0, fm);
    R = fi(1e2*eye(4), 0, 7, 0, fm);
    
%     x = [1 0 0 0]';
    P = fi(1*eye(4), 1, 16, 11, fm);
    
    firstRun = fi(1, 0, 1, 0, fm);
end

xp = fi(A*x, 1, 16, 15, fm);
Pp = fi(A*P*A' + Q, 1, 16, 11, fm);

K = fi(Pp*H'*inv(fi_toint(H*Pp*H' + R)), 1, 16, 18, fm);

x = fi(xp + K*(z - H*xp), 1, 16, 15, fm);
P(:) = Pp - K*H*Pp;

phi = fi(atan2( fi(2, 0, 2, 0, fm)*(x(3)*x(4) +x(1)*x(2)), fi(1, 0, 1, 0, fm)- fi(2, 0, 2, 0, fm)*(x(2)^2+x(3)^2) ), 1, 16, 17, fm);
theta = fi(fi_uminus(asin(fi(2, 0, 2, 0, fm)*(fi_signed(x(2)*x(4)) -x(1)*x(3)) )), 1, 16, 17, fm);
psi = fi(atan2(fi(2, 0, 2, 0, fm)*(x(2)*x(3) + x(1)*x(4)), fi_signed(fi(1, 0, 1, 0, fm))-fi(2, 0, 2, 0, fm)*(x(3)^2 +x(4)^2) ), 1, 16, 13, fm);
end



function ntype = divideType(a,b)
    coder.inline( 'always' );
    nt1 = numerictype( a );
    nt2 = numerictype( b );
    maxFL = max( [ min( nt1.WordLength, nt1.FractionLength ), min( nt2.WordLength, nt2.FractionLength ) ] );
    FL = max( maxFL, 24 );
    extraBits = (FL - maxFL);
    WL = nt1.WordLength + nt2.WordLength;
    WL = min( WL, 124 );
    if (WL + extraBits)<64
        ntype = numerictype( nt1.Signed || nt2.Signed, WL + extraBits, FL );
    else
        ntype = numerictype( nt1.Signed || nt2.Signed, WL, FL );
    end
end


function c = fi_div(a,b)
    coder.inline( 'always' );
    a1 = fi( a, 'RoundMode', 'fix' );
    b1 = fi( b, 'RoundMode', 'fix' );
    nType = divideType( a1, b1 );
    if isfi( a ) && isfi( b ) && isscalar( b )
        c1 = divide( nType, a1, b1 );
        c = fi( c1, numerictype( c1 ), fimath( a ) );
    else
        c = fi( a / b, nType );
    end
end


function y = fi_div_by_shift(a,shift_len)
    coder.inline( 'always' );
    if isfi( a )
        nt = numerictype( a );
        fm = fimath( a );
        nt_bs = numerictype( nt.Signed, nt.WordLength + shift_len, nt.FractionLength + shift_len );
        y = bitsra( fi( a, nt_bs, fm ), shift_len );
    else
        y = a / 2 ^ shift_len;
    end
end


function y = fi_signed(a)
    coder.inline( 'always' );
    if isfi( a ) && ~(issigned( a ))
        nt = numerictype( a );
        new_nt = numerictype( 1, nt.WordLength + 1, nt.FractionLength );
        y = fi( a, new_nt, fimath( a ) );
    else
        y = a;
    end
end


function y = fi_toint(u)
    coder.inline( 'always' );
    if isfi( u )
        nt = numerictype( u );
        s = nt.SignednessBool;
        wl = nt.WordLength;
        y = int32( fi( u, s, wl, 0, hdlfimath ) );
    else
        y = int32( u );
    end
end


function y = fi_uminus(a)
    coder.inline( 'always' );
    if isfi( a )
        nt = numerictype( a );
        new_nt = numerictype( 1, nt.WordLength + 1, nt.FractionLength );
        y = -fi( a, new_nt, fimath( a ) );
    else
        y = -a;
    end
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
