// Generated by gencpp from file ipe/Fusion.msg
// DO NOT EDIT!


#ifndef IPE_MESSAGE_FUSION_H
#define IPE_MESSAGE_FUSION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ipe
{
template <class ContainerAllocator>
struct Fusion_
{
  typedef Fusion_<ContainerAllocator> Type;

  Fusion_()
    : header()
    , kf_psi(0.0)
    , gyro_psi(0.0)
    , cent_pos_est()
    , cent_vel_est()
    , prevTagHeading(0.0)
    , init_flag(0.0)
    , prevTagPos()
    , acc_b_phi(0.0)  {
    }
  Fusion_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , kf_psi(0.0)
    , gyro_psi(0.0)
    , cent_pos_est(_alloc)
    , cent_vel_est(_alloc)
    , prevTagHeading(0.0)
    , init_flag(0.0)
    , prevTagPos(_alloc)
    , acc_b_phi(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _kf_psi_type;
  _kf_psi_type kf_psi;

   typedef double _gyro_psi_type;
  _gyro_psi_type gyro_psi;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _cent_pos_est_type;
  _cent_pos_est_type cent_pos_est;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _cent_vel_est_type;
  _cent_vel_est_type cent_vel_est;

   typedef double _prevTagHeading_type;
  _prevTagHeading_type prevTagHeading;

   typedef double _init_flag_type;
  _init_flag_type init_flag;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _prevTagPos_type;
  _prevTagPos_type prevTagPos;

   typedef double _acc_b_phi_type;
  _acc_b_phi_type acc_b_phi;





  typedef boost::shared_ptr< ::ipe::Fusion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ipe::Fusion_<ContainerAllocator> const> ConstPtr;

}; // struct Fusion_

typedef ::ipe::Fusion_<std::allocator<void> > Fusion;

typedef boost::shared_ptr< ::ipe::Fusion > FusionPtr;
typedef boost::shared_ptr< ::ipe::Fusion const> FusionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ipe::Fusion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ipe::Fusion_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ipe::Fusion_<ContainerAllocator1> & lhs, const ::ipe::Fusion_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.kf_psi == rhs.kf_psi &&
    lhs.gyro_psi == rhs.gyro_psi &&
    lhs.cent_pos_est == rhs.cent_pos_est &&
    lhs.cent_vel_est == rhs.cent_vel_est &&
    lhs.prevTagHeading == rhs.prevTagHeading &&
    lhs.init_flag == rhs.init_flag &&
    lhs.prevTagPos == rhs.prevTagPos &&
    lhs.acc_b_phi == rhs.acc_b_phi;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ipe::Fusion_<ContainerAllocator1> & lhs, const ::ipe::Fusion_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ipe

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ipe::Fusion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ipe::Fusion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ipe::Fusion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ipe::Fusion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ipe::Fusion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ipe::Fusion_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ipe::Fusion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "15f601fb989711f5c196163f3ad3e1f7";
  }

  static const char* value(const ::ipe::Fusion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x15f601fb989711f5ULL;
  static const uint64_t static_value2 = 0xc196163f3ad3e1f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ipe::Fusion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ipe/Fusion";
  }

  static const char* value(const ::ipe::Fusion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ipe::Fusion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64 kf_psi\n"
"float64 gyro_psi\n"
"float64[] cent_pos_est\n"
"float64[] cent_vel_est\n"
"float64 prevTagHeading\n"
"float64 init_flag\n"
"float64[] prevTagPos\n"
"float64 acc_b_phi\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ipe::Fusion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ipe::Fusion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.kf_psi);
      stream.next(m.gyro_psi);
      stream.next(m.cent_pos_est);
      stream.next(m.cent_vel_est);
      stream.next(m.prevTagHeading);
      stream.next(m.init_flag);
      stream.next(m.prevTagPos);
      stream.next(m.acc_b_phi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Fusion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ipe::Fusion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ipe::Fusion_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "kf_psi: ";
    Printer<double>::stream(s, indent + "  ", v.kf_psi);
    s << indent << "gyro_psi: ";
    Printer<double>::stream(s, indent + "  ", v.gyro_psi);
    s << indent << "cent_pos_est[]" << std::endl;
    for (size_t i = 0; i < v.cent_pos_est.size(); ++i)
    {
      s << indent << "  cent_pos_est[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.cent_pos_est[i]);
    }
    s << indent << "cent_vel_est[]" << std::endl;
    for (size_t i = 0; i < v.cent_vel_est.size(); ++i)
    {
      s << indent << "  cent_vel_est[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.cent_vel_est[i]);
    }
    s << indent << "prevTagHeading: ";
    Printer<double>::stream(s, indent + "  ", v.prevTagHeading);
    s << indent << "init_flag: ";
    Printer<double>::stream(s, indent + "  ", v.init_flag);
    s << indent << "prevTagPos[]" << std::endl;
    for (size_t i = 0; i < v.prevTagPos.size(); ++i)
    {
      s << indent << "  prevTagPos[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.prevTagPos[i]);
    }
    s << indent << "acc_b_phi: ";
    Printer<double>::stream(s, indent + "  ", v.acc_b_phi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IPE_MESSAGE_FUSION_H
