// Generated by gencpp from file ipe/Imupos.msg
// DO NOT EDIT!


#ifndef IPE_MESSAGE_IMUPOS_H
#define IPE_MESSAGE_IMUPOS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ipe
{
template <class ContainerAllocator>
struct Imupos_
{
  typedef Imupos_<ContainerAllocator> Type;

  Imupos_()
    : header()
    , b_acc_o()
    , b_gyro()
    , mode(0.0)
    , kf_psi(0.0)
    , gyro_psi(0.0)
    , cent_pos_est()
    , cent_vel_est()
    , state_o(0.0)
    , acc_b_phi(0.0)
    , acc_b_theta(0.0)  {
    }
  Imupos_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , b_acc_o(_alloc)
    , b_gyro(_alloc)
    , mode(0.0)
    , kf_psi(0.0)
    , gyro_psi(0.0)
    , cent_pos_est(_alloc)
    , cent_vel_est(_alloc)
    , state_o(0.0)
    , acc_b_phi(0.0)
    , acc_b_theta(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _b_acc_o_type;
  _b_acc_o_type b_acc_o;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _b_gyro_type;
  _b_gyro_type b_gyro;

   typedef double _mode_type;
  _mode_type mode;

   typedef double _kf_psi_type;
  _kf_psi_type kf_psi;

   typedef double _gyro_psi_type;
  _gyro_psi_type gyro_psi;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _cent_pos_est_type;
  _cent_pos_est_type cent_pos_est;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _cent_vel_est_type;
  _cent_vel_est_type cent_vel_est;

   typedef double _state_o_type;
  _state_o_type state_o;

   typedef double _acc_b_phi_type;
  _acc_b_phi_type acc_b_phi;

   typedef double _acc_b_theta_type;
  _acc_b_theta_type acc_b_theta;





  typedef boost::shared_ptr< ::ipe::Imupos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ipe::Imupos_<ContainerAllocator> const> ConstPtr;

}; // struct Imupos_

typedef ::ipe::Imupos_<std::allocator<void> > Imupos;

typedef boost::shared_ptr< ::ipe::Imupos > ImuposPtr;
typedef boost::shared_ptr< ::ipe::Imupos const> ImuposConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ipe::Imupos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ipe::Imupos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ipe::Imupos_<ContainerAllocator1> & lhs, const ::ipe::Imupos_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.b_acc_o == rhs.b_acc_o &&
    lhs.b_gyro == rhs.b_gyro &&
    lhs.mode == rhs.mode &&
    lhs.kf_psi == rhs.kf_psi &&
    lhs.gyro_psi == rhs.gyro_psi &&
    lhs.cent_pos_est == rhs.cent_pos_est &&
    lhs.cent_vel_est == rhs.cent_vel_est &&
    lhs.state_o == rhs.state_o &&
    lhs.acc_b_phi == rhs.acc_b_phi &&
    lhs.acc_b_theta == rhs.acc_b_theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ipe::Imupos_<ContainerAllocator1> & lhs, const ::ipe::Imupos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ipe

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ipe::Imupos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ipe::Imupos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ipe::Imupos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ipe::Imupos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ipe::Imupos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ipe::Imupos_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ipe::Imupos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7b3c908ac554cd386d59718bc4de7e4";
  }

  static const char* value(const ::ipe::Imupos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7b3c908ac554cd3ULL;
  static const uint64_t static_value2 = 0x86d59718bc4de7e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::ipe::Imupos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ipe/Imupos";
  }

  static const char* value(const ::ipe::Imupos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ipe::Imupos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64[] b_acc_o\n"
"float64[] b_gyro\n"
"float64 mode\n"
"float64 kf_psi\n"
"float64 gyro_psi\n"
"float64[] cent_pos_est\n"
"float64[] cent_vel_est\n"
"float64 state_o\n"
"float64 acc_b_phi\n"
"float64 acc_b_theta\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ipe::Imupos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ipe::Imupos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.b_acc_o);
      stream.next(m.b_gyro);
      stream.next(m.mode);
      stream.next(m.kf_psi);
      stream.next(m.gyro_psi);
      stream.next(m.cent_pos_est);
      stream.next(m.cent_vel_est);
      stream.next(m.state_o);
      stream.next(m.acc_b_phi);
      stream.next(m.acc_b_theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Imupos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ipe::Imupos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ipe::Imupos_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "b_acc_o[]" << std::endl;
    for (size_t i = 0; i < v.b_acc_o.size(); ++i)
    {
      s << indent << "  b_acc_o[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.b_acc_o[i]);
    }
    s << indent << "b_gyro[]" << std::endl;
    for (size_t i = 0; i < v.b_gyro.size(); ++i)
    {
      s << indent << "  b_gyro[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.b_gyro[i]);
    }
    s << indent << "mode: ";
    Printer<double>::stream(s, indent + "  ", v.mode);
    s << indent << "kf_psi: ";
    Printer<double>::stream(s, indent + "  ", v.kf_psi);
    s << indent << "gyro_psi: ";
    Printer<double>::stream(s, indent + "  ", v.gyro_psi);
    s << indent << "cent_pos_est[]" << std::endl;
    for (size_t i = 0; i < v.cent_pos_est.size(); ++i)
    {
      s << indent << "  cent_pos_est[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.cent_pos_est[i]);
    }
    s << indent << "cent_vel_est[]" << std::endl;
    for (size_t i = 0; i < v.cent_vel_est.size(); ++i)
    {
      s << indent << "  cent_vel_est[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.cent_vel_est[i]);
    }
    s << indent << "state_o: ";
    Printer<double>::stream(s, indent + "  ", v.state_o);
    s << indent << "acc_b_phi: ";
    Printer<double>::stream(s, indent + "  ", v.acc_b_phi);
    s << indent << "acc_b_theta: ";
    Printer<double>::stream(s, indent + "  ", v.acc_b_theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IPE_MESSAGE_IMUPOS_H
