// Generated by gencpp from file ipe/Uwbpos.msg
// DO NOT EDIT!


#ifndef IPE_MESSAGE_UWBPOS_H
#define IPE_MESSAGE_UWBPOS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ipe
{
template <class ContainerAllocator>
struct Uwbpos_
{
  typedef Uwbpos_<ContainerAllocator> Type;

  Uwbpos_()
    : header()
    , tag_center_vel_est()
    , tag_pos_est()
    , tag_pos_b()
    , UWBErrSum(0.0)
    , heading_est(0.0)
    , Nanchor(0.0)
    , init_flag(0.0)
    , zt_b(0.0)  {
    }
  Uwbpos_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tag_center_vel_est(_alloc)
    , tag_pos_est(_alloc)
    , tag_pos_b(_alloc)
    , UWBErrSum(0.0)
    , heading_est(0.0)
    , Nanchor(0.0)
    , init_flag(0.0)
    , zt_b(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _tag_center_vel_est_type;
  _tag_center_vel_est_type tag_center_vel_est;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _tag_pos_est_type;
  _tag_pos_est_type tag_pos_est;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _tag_pos_b_type;
  _tag_pos_b_type tag_pos_b;

   typedef double _UWBErrSum_type;
  _UWBErrSum_type UWBErrSum;

   typedef double _heading_est_type;
  _heading_est_type heading_est;

   typedef double _Nanchor_type;
  _Nanchor_type Nanchor;

   typedef double _init_flag_type;
  _init_flag_type init_flag;

   typedef double _zt_b_type;
  _zt_b_type zt_b;





  typedef boost::shared_ptr< ::ipe::Uwbpos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ipe::Uwbpos_<ContainerAllocator> const> ConstPtr;

}; // struct Uwbpos_

typedef ::ipe::Uwbpos_<std::allocator<void> > Uwbpos;

typedef boost::shared_ptr< ::ipe::Uwbpos > UwbposPtr;
typedef boost::shared_ptr< ::ipe::Uwbpos const> UwbposConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ipe::Uwbpos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ipe::Uwbpos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ipe::Uwbpos_<ContainerAllocator1> & lhs, const ::ipe::Uwbpos_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.tag_center_vel_est == rhs.tag_center_vel_est &&
    lhs.tag_pos_est == rhs.tag_pos_est &&
    lhs.tag_pos_b == rhs.tag_pos_b &&
    lhs.UWBErrSum == rhs.UWBErrSum &&
    lhs.heading_est == rhs.heading_est &&
    lhs.Nanchor == rhs.Nanchor &&
    lhs.init_flag == rhs.init_flag &&
    lhs.zt_b == rhs.zt_b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ipe::Uwbpos_<ContainerAllocator1> & lhs, const ::ipe::Uwbpos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ipe

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ipe::Uwbpos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ipe::Uwbpos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ipe::Uwbpos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ipe::Uwbpos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ipe::Uwbpos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ipe::Uwbpos_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ipe::Uwbpos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5e368833065ec31ffd718a3d27ee9f6";
  }

  static const char* value(const ::ipe::Uwbpos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5e368833065ec31ULL;
  static const uint64_t static_value2 = 0xffd718a3d27ee9f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::ipe::Uwbpos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ipe/Uwbpos";
  }

  static const char* value(const ::ipe::Uwbpos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ipe::Uwbpos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64[] tag_center_vel_est\n"
"float64[] tag_pos_est\n"
"float64[] tag_pos_b\n"
"float64 UWBErrSum\n"
"float64 heading_est\n"
"float64 Nanchor\n"
"float64 init_flag\n"
"float64 zt_b\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ipe::Uwbpos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ipe::Uwbpos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tag_center_vel_est);
      stream.next(m.tag_pos_est);
      stream.next(m.tag_pos_b);
      stream.next(m.UWBErrSum);
      stream.next(m.heading_est);
      stream.next(m.Nanchor);
      stream.next(m.init_flag);
      stream.next(m.zt_b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Uwbpos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ipe::Uwbpos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ipe::Uwbpos_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tag_center_vel_est[]" << std::endl;
    for (size_t i = 0; i < v.tag_center_vel_est.size(); ++i)
    {
      s << indent << "  tag_center_vel_est[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.tag_center_vel_est[i]);
    }
    s << indent << "tag_pos_est[]" << std::endl;
    for (size_t i = 0; i < v.tag_pos_est.size(); ++i)
    {
      s << indent << "  tag_pos_est[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.tag_pos_est[i]);
    }
    s << indent << "tag_pos_b[]" << std::endl;
    for (size_t i = 0; i < v.tag_pos_b.size(); ++i)
    {
      s << indent << "  tag_pos_b[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.tag_pos_b[i]);
    }
    s << indent << "UWBErrSum: ";
    Printer<double>::stream(s, indent + "  ", v.UWBErrSum);
    s << indent << "heading_est: ";
    Printer<double>::stream(s, indent + "  ", v.heading_est);
    s << indent << "Nanchor: ";
    Printer<double>::stream(s, indent + "  ", v.Nanchor);
    s << indent << "init_flag: ";
    Printer<double>::stream(s, indent + "  ", v.init_flag);
    s << indent << "zt_b: ";
    Printer<double>::stream(s, indent + "  ", v.zt_b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IPE_MESSAGE_UWBPOS_H
