// Generated by gencpp from file localizer_dwm1001/Anchor.msg
// DO NOT EDIT!


#ifndef LOCALIZER_DWM1001_MESSAGE_ANCHOR_H
#define LOCALIZER_DWM1001_MESSAGE_ANCHOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace localizer_dwm1001
{
template <class ContainerAllocator>
struct Anchor_
{
  typedef Anchor_<ContainerAllocator> Type;

  Anchor_()
    : header()
    , id()
    , x()
    , y()
    , z()
    , distanceFromTag()  {
    }
  Anchor_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(_alloc)
    , x(_alloc)
    , y(_alloc)
    , z(_alloc)
    , distanceFromTag(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _id_type;
  _id_type id;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _x_type;
  _x_type x;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _y_type;
  _y_type y;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _z_type;
  _z_type z;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _distanceFromTag_type;
  _distanceFromTag_type distanceFromTag;





  typedef boost::shared_ptr< ::localizer_dwm1001::Anchor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localizer_dwm1001::Anchor_<ContainerAllocator> const> ConstPtr;

}; // struct Anchor_

typedef ::localizer_dwm1001::Anchor_<std::allocator<void> > Anchor;

typedef boost::shared_ptr< ::localizer_dwm1001::Anchor > AnchorPtr;
typedef boost::shared_ptr< ::localizer_dwm1001::Anchor const> AnchorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localizer_dwm1001::Anchor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localizer_dwm1001::Anchor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::localizer_dwm1001::Anchor_<ContainerAllocator1> & lhs, const ::localizer_dwm1001::Anchor_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.distanceFromTag == rhs.distanceFromTag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::localizer_dwm1001::Anchor_<ContainerAllocator1> & lhs, const ::localizer_dwm1001::Anchor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace localizer_dwm1001

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::localizer_dwm1001::Anchor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localizer_dwm1001::Anchor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localizer_dwm1001::Anchor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localizer_dwm1001::Anchor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localizer_dwm1001::Anchor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localizer_dwm1001::Anchor_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localizer_dwm1001::Anchor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f20b9f16268fafcfc83cd35dc1a9f0e";
  }

  static const char* value(const ::localizer_dwm1001::Anchor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f20b9f16268fafcULL;
  static const uint64_t static_value2 = 0xfc83cd35dc1a9f0eULL;
};

template<class ContainerAllocator>
struct DataType< ::localizer_dwm1001::Anchor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localizer_dwm1001/Anchor";
  }

  static const char* value(const ::localizer_dwm1001::Anchor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localizer_dwm1001::Anchor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string[]   id\n"
"float64[]  x\n"
"float64[]  y\n"
"float64[]  z\n"
"float64[]  distanceFromTag\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::localizer_dwm1001::Anchor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localizer_dwm1001::Anchor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.distanceFromTag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Anchor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localizer_dwm1001::Anchor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localizer_dwm1001::Anchor_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id[]" << std::endl;
    for (size_t i = 0; i < v.id.size(); ++i)
    {
      s << indent << "  id[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.id[i]);
    }
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "z[]" << std::endl;
    for (size_t i = 0; i < v.z.size(); ++i)
    {
      s << indent << "  z[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.z[i]);
    }
    s << indent << "distanceFromTag[]" << std::endl;
    for (size_t i = 0; i < v.distanceFromTag.size(); ++i)
    {
      s << indent << "  distanceFromTag[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.distanceFromTag[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZER_DWM1001_MESSAGE_ANCHOR_H
