/*
 * makePredA_3D_Simple.c
 *
 * Code generation for function 'makePredA_3D_Simple'
 *
 */

/* Include files */
#include "makePredA_3D_Simple.h"
#include "rt_nonfinite.h"
#include <math.h>
#include <string.h>

/* Function Definitions */
void makePredA_3D_Simple(const double Xhat[15], const double acc[3],
                         const double p[3], double dT, double A[225])
{
  static const signed char j_a[9] = {1, 0, 0, 0, 1, 0, 0, 0, 1};
  static const signed char b[3] = {-1, 0, 0};
  static const signed char b_b[3] = {0, -1, 0};
  static const signed char c_b[3] = {0, 0, -1};
  double RotMat[9];
  double RotMatRalp[9];
  double RotMatRbet[9];
  double RotMatRgam[9];
  double ZyroUpdateRbet[9];
  double b_tmp[3];
  double A_tmp;
  double RotMat_tmp;
  double RotMat_tmp_tmp;
  double ZyroUpdate_tmp;
  double a;
  double b_A_tmp;
  double b_RotMat_tmp;
  double b_RotMat_tmp_tmp;
  double b_a;
  double b_dT;
  double c_A_tmp;
  double c_RotMat_tmp;
  double c_RotMat_tmp_tmp;
  double c_a;
  double c_dT;
  double d;
  double d1;
  double d2;
  double d3;
  double d_A_tmp;
  double d_RotMat_tmp;
  double d_RotMat_tmp_tmp;
  double d_a;
  double d_dT;
  double e_A_tmp;
  double e_RotMat_tmp;
  double e_RotMat_tmp_tmp;
  double e_a;
  double e_dT;
  double f_A_tmp;
  double f_RotMat_tmp;
  double f_a;
  double f_dT;
  double g_A_tmp;
  double g_RotMat_tmp;
  double g_a;
  double g_dT;
  double h_A_tmp;
  double h_RotMat_tmp;
  double h_a;
  double h_dT;
  double i_A_tmp;
  double i_RotMat_tmp;
  double i_a;
  double i_dT;
  double j_RotMat_tmp;
  double j_dT;
  int i;
  int k;
  memset(&A[0], 0, 225U * sizeof(double));
  for (k = 0; k < 15; k++) {
    A[k + 15 * k] = 1.0;
  }
  RotMat_tmp_tmp = sin(Xhat[9]);
  RotMat_tmp = cos(Xhat[11]);
  b_RotMat_tmp = cos(Xhat[9]);
  b_RotMat_tmp_tmp = sin(Xhat[11]);
  c_RotMat_tmp_tmp = cos(Xhat[10]);
  d_RotMat_tmp_tmp = sin(Xhat[10]);
  c_RotMat_tmp = RotMat_tmp_tmp * c_RotMat_tmp_tmp;
  RotMat[0] = c_RotMat_tmp;
  d_RotMat_tmp = RotMat_tmp_tmp * d_RotMat_tmp_tmp;
  e_RotMat_tmp = b_RotMat_tmp * RotMat_tmp;
  RotMat[3] = d_RotMat_tmp * b_RotMat_tmp_tmp + e_RotMat_tmp;
  f_RotMat_tmp = b_RotMat_tmp * b_RotMat_tmp_tmp;
  d_RotMat_tmp = d_RotMat_tmp * RotMat_tmp - f_RotMat_tmp;
  RotMat[6] = d_RotMat_tmp;
  g_RotMat_tmp = b_RotMat_tmp * c_RotMat_tmp_tmp;
  RotMat[1] = g_RotMat_tmp;
  h_RotMat_tmp = b_RotMat_tmp * d_RotMat_tmp_tmp;
  e_RotMat_tmp_tmp = RotMat_tmp_tmp * RotMat_tmp;
  i_RotMat_tmp = h_RotMat_tmp * b_RotMat_tmp_tmp - e_RotMat_tmp_tmp;
  RotMat[4] = i_RotMat_tmp;
  h_RotMat_tmp = h_RotMat_tmp * RotMat_tmp + RotMat_tmp_tmp * b_RotMat_tmp_tmp;
  RotMat[7] = h_RotMat_tmp;
  RotMat[2] = -d_RotMat_tmp_tmp;
  RotMat[5] = c_RotMat_tmp_tmp * b_RotMat_tmp_tmp;
  j_RotMat_tmp = c_RotMat_tmp_tmp * RotMat_tmp;
  RotMat[8] = j_RotMat_tmp;
  RotMatRalp[0] = g_RotMat_tmp;
  RotMatRalp[3] = i_RotMat_tmp;
  RotMatRalp[6] = h_RotMat_tmp;
  RotMatRalp[1] = -RotMat_tmp_tmp * c_RotMat_tmp_tmp;
  RotMat_tmp_tmp = -RotMat_tmp_tmp * d_RotMat_tmp_tmp;
  i_RotMat_tmp = RotMat_tmp_tmp * b_RotMat_tmp_tmp - e_RotMat_tmp;
  RotMatRalp[4] = i_RotMat_tmp;
  RotMatRalp[7] = RotMat_tmp_tmp * RotMat_tmp + f_RotMat_tmp;
  RotMatRbet[0] = RotMat_tmp_tmp;
  RotMatRbet[3] = c_RotMat_tmp * b_RotMat_tmp_tmp;
  RotMatRbet[6] = c_RotMat_tmp * RotMat_tmp;
  RotMat_tmp_tmp = -b_RotMat_tmp * d_RotMat_tmp_tmp;
  RotMatRbet[1] = RotMat_tmp_tmp;
  RotMatRbet[4] = g_RotMat_tmp * b_RotMat_tmp_tmp;
  RotMatRbet[7] = g_RotMat_tmp * RotMat_tmp;
  RotMatRbet[2] = -c_RotMat_tmp_tmp;
  RotMatRbet[5] = -d_RotMat_tmp_tmp * b_RotMat_tmp_tmp;
  RotMatRbet[8] = -d_RotMat_tmp_tmp * RotMat_tmp;
  RotMatRgam[0] = 0.0;
  RotMatRgam[3] = d_RotMat_tmp;
  RotMatRgam[6] = i_RotMat_tmp;
  RotMatRgam[1] = 0.0;
  RotMatRgam[4] = h_RotMat_tmp;
  RotMatRgam[7] = RotMat_tmp_tmp * b_RotMat_tmp_tmp + e_RotMat_tmp_tmp;
  RotMatRgam[2] = 0.0;
  RotMatRgam[5] = j_RotMat_tmp;
  RotMatRgam[8] = -c_RotMat_tmp_tmp * b_RotMat_tmp_tmp;
  ZyroUpdate_tmp = tan(Xhat[10]);
  RotMat_tmp_tmp = c_RotMat_tmp_tmp * c_RotMat_tmp_tmp;
  ZyroUpdateRbet[3] = b_RotMat_tmp_tmp / RotMat_tmp_tmp;
  ZyroUpdateRbet[6] = RotMat_tmp / RotMat_tmp_tmp;
  ZyroUpdateRbet[5] = b_RotMat_tmp_tmp * d_RotMat_tmp_tmp / RotMat_tmp_tmp;
  ZyroUpdateRbet[8] = RotMat_tmp * d_RotMat_tmp_tmp / RotMat_tmp_tmp;
  e_RotMat_tmp = 0.5 * (dT * dT);
  b_RotMat_tmp = 0.0;
  c_RotMat_tmp = 0.0;
  f_RotMat_tmp = 0.0;
  b_tmp[0] = acc[0] - Xhat[6];
  b_tmp[1] = acc[1] - Xhat[7];
  b_tmp[2] = acc[2] - Xhat[8];
  d_RotMat_tmp = 0.0;
  g_RotMat_tmp = 0.0;
  h_RotMat_tmp = 0.0;
  e_RotMat_tmp_tmp = 0.0;
  j_RotMat_tmp = 0.0;
  d_RotMat_tmp_tmp = 0.0;
  a = 0.0;
  b_a = 0.0;
  c_a = 0.0;
  d_a = 0.0;
  e_a = 0.0;
  f_a = 0.0;
  g_a = 0.0;
  h_a = 0.0;
  i_a = 0.0;
  A_tmp = 0.0;
  b_A_tmp = 0.0;
  c_A_tmp = 0.0;
  b_dT = 0.0;
  c_dT = 0.0;
  d_dT = 0.0;
  d_A_tmp = 0.0;
  e_A_tmp = 0.0;
  f_A_tmp = 0.0;
  e_dT = 0.0;
  f_dT = 0.0;
  g_dT = 0.0;
  g_A_tmp = 0.0;
  h_A_tmp = 0.0;
  i_A_tmp = 0.0;
  h_dT = 0.0;
  i_dT = 0.0;
  j_dT = 0.0;
  for (i = 0; i < 3; i++) {
    double d4;
    double d5;
    double d6;
    double d7;
    double d8;
    double d9;
    int RotMatRalp_tmp;
    int ZyroUpdateRbet_tmp;
    int a_tmp;
    int b_a_tmp;
    RotMatRalp_tmp = 3 * i + 2;
    RotMatRalp[RotMatRalp_tmp] = 0.0;
    ZyroUpdateRbet_tmp = 3 * i + 1;
    ZyroUpdateRbet[ZyroUpdateRbet_tmp] = 0.0;
    k = 15 * (i + 3);
    A[k] = (double)j_a[3 * i] * dT;
    A[k + 1] = (double)j_a[ZyroUpdateRbet_tmp] * dT;
    A[k + 2] = (double)j_a[RotMatRalp_tmp] * dT;
    d = RotMat[3 * i];
    RotMat_tmp_tmp = e_RotMat_tmp * d;
    k = b[i];
    b_RotMat_tmp += RotMat_tmp_tmp * (double)k;
    a_tmp = b_b[i];
    c_RotMat_tmp += RotMat_tmp_tmp * (double)a_tmp;
    b_a_tmp = c_b[i];
    f_RotMat_tmp += RotMat_tmp_tmp * (double)b_a_tmp;
    d1 = RotMatRalp[3 * i];
    d2 = b_tmp[i];
    d_RotMat_tmp += e_RotMat_tmp * d1 * d2;
    d3 = RotMatRbet[3 * i];
    g_RotMat_tmp += e_RotMat_tmp * d3 * d2;
    d4 = RotMatRgam[3 * i];
    h_RotMat_tmp += e_RotMat_tmp * d4 * d2;
    d5 = RotMat[ZyroUpdateRbet_tmp];
    RotMat_tmp_tmp = e_RotMat_tmp * d5;
    e_RotMat_tmp_tmp += RotMat_tmp_tmp * (double)k;
    j_RotMat_tmp += RotMat_tmp_tmp * (double)a_tmp;
    d_RotMat_tmp_tmp += RotMat_tmp_tmp * (double)b_a_tmp;
    d6 = RotMatRalp[ZyroUpdateRbet_tmp];
    a += e_RotMat_tmp * d6 * d2;
    d7 = RotMatRbet[ZyroUpdateRbet_tmp];
    b_a += e_RotMat_tmp * d7 * d2;
    d8 = RotMatRgam[ZyroUpdateRbet_tmp];
    c_a += e_RotMat_tmp * d8 * d2;
    d9 = RotMat[RotMatRalp_tmp];
    RotMat_tmp_tmp = e_RotMat_tmp * d9;
    d_a += RotMat_tmp_tmp * (double)k;
    e_a += RotMat_tmp_tmp * (double)a_tmp;
    f_a += RotMat_tmp_tmp * (double)b_a_tmp;
    g_a += e_RotMat_tmp * 0.0 * d2;
    RotMat_tmp_tmp = RotMatRbet[RotMatRalp_tmp];
    h_a += e_RotMat_tmp * RotMat_tmp_tmp * d2;
    i_RotMat_tmp = RotMatRgam[RotMatRalp_tmp];
    i_a += e_RotMat_tmp * i_RotMat_tmp * d2;
    d *= dT;
    A_tmp += d * (double)k;
    b_A_tmp += d * (double)a_tmp;
    c_A_tmp += d * (double)b_a_tmp;
    b_dT += dT * d1 * d2;
    c_dT += dT * d3 * d2;
    d_dT += dT * d4 * d2;
    d = dT * d5;
    d_A_tmp += d * (double)k;
    e_A_tmp += d * (double)a_tmp;
    f_A_tmp += d * (double)b_a_tmp;
    e_dT += dT * d6 * d2;
    f_dT += dT * d7 * d2;
    g_dT += dT * d8 * d2;
    d = dT * d9;
    g_A_tmp += d * (double)k;
    h_A_tmp += d * (double)a_tmp;
    i_A_tmp += d * (double)b_a_tmp;
    h_dT += dT * 0.0 * d2;
    i_dT += dT * RotMat_tmp_tmp * d2;
    j_dT += dT * i_RotMat_tmp * d2;
  }
  A[90] = b_RotMat_tmp;
  A[105] = c_RotMat_tmp;
  A[120] = f_RotMat_tmp;
  A[135] = d_RotMat_tmp;
  A[150] = g_RotMat_tmp;
  A[165] = h_RotMat_tmp;
  A[91] = e_RotMat_tmp_tmp;
  A[106] = j_RotMat_tmp;
  A[121] = d_RotMat_tmp_tmp;
  A[136] = a;
  A[151] = b_a;
  A[166] = c_a;
  A[92] = d_a;
  A[107] = e_a;
  A[122] = f_a;
  A[137] = g_a;
  A[152] = h_a;
  A[167] = i_a;
  A[93] = A_tmp;
  A[108] = b_A_tmp;
  A[123] = c_A_tmp;
  A[138] = b_dT;
  A[153] = c_dT;
  A[168] = d_dT;
  A[94] = d_A_tmp;
  A[109] = e_A_tmp;
  A[124] = f_A_tmp;
  A[139] = e_dT;
  A[154] = f_dT;
  A[169] = g_dT;
  A[95] = g_A_tmp;
  A[110] = h_A_tmp;
  A[125] = i_A_tmp;
  A[140] = h_dT;
  A[155] = i_dT;
  A[170] = j_dT;
  b_tmp[1] = p[1] - Xhat[13];
  b_tmp[2] = p[2] - Xhat[14];
  i_RotMat_tmp = dT * 0.0 * (p[0] - Xhat[12]);
  A_tmp = dT * 0.0;
  RotMat_tmp_tmp = A_tmp * 0.0;
  d = dT * (b_RotMat_tmp_tmp / c_RotMat_tmp_tmp);
  b_A_tmp = -A_tmp + d * 0.0;
  c_A_tmp = RotMat_tmp_tmp - d;
  d_A_tmp = RotMat_tmp_tmp + d * 0.0;
  d = dT * RotMat_tmp;
  e_A_tmp = -A_tmp + d * 0.0;
  f_A_tmp = RotMat_tmp_tmp - d;
  g_A_tmp = RotMat_tmp_tmp + d * 0.0;
  d = dT * (b_RotMat_tmp_tmp * ZyroUpdate_tmp);
  RotMat_tmp_tmp = (i_RotMat_tmp + dT * 0.0 * b_tmp[1]) + dT * 0.0 * b_tmp[2];
  d1 = dT * (RotMat_tmp / c_RotMat_tmp_tmp);
  b_A_tmp += d1 * 0.0;
  c_A_tmp += d1 * 0.0;
  d_A_tmp -= d1;
  d2 = dT * -b_RotMat_tmp_tmp;
  e_A_tmp += d2 * 0.0;
  f_A_tmp += d2 * 0.0;
  g_A_tmp -= d2;
  d3 = dT * (RotMat_tmp * ZyroUpdate_tmp);
  A[174] = ((i_RotMat_tmp + d1 * b_tmp[1]) +
            dT * (-b_RotMat_tmp_tmp / c_RotMat_tmp_tmp) * b_tmp[2]) +
           1.0;
  A[159] = (i_RotMat_tmp + dT * ZyroUpdateRbet[5] * b_tmp[1]) +
           dT * ZyroUpdateRbet[8] * b_tmp[2];
  A[144] = RotMat_tmp_tmp;
  A[189] = b_A_tmp;
  A[204] = c_A_tmp;
  A[219] = d_A_tmp;
  A[175] = (i_RotMat_tmp + d2 * b_tmp[1]) + dT * -RotMat_tmp * b_tmp[2];
  A[160] = RotMat_tmp_tmp + 1.0;
  A[145] = RotMat_tmp_tmp;
  A[190] = e_A_tmp;
  A[205] = f_A_tmp;
  A[220] = g_A_tmp;
  A[176] = (i_RotMat_tmp + d3 * b_tmp[1]) +
           dT * (-b_RotMat_tmp_tmp * ZyroUpdate_tmp) * b_tmp[2];
  A[161] = (i_RotMat_tmp + dT * ZyroUpdateRbet[3] * b_tmp[1]) +
           dT * ZyroUpdateRbet[6] * b_tmp[2];
  A[146] = RotMat_tmp_tmp + 1.0;
  A[191] = (-dT + d * 0.0) + d3 * 0.0;
  A[206] = (A_tmp - d) + d3 * 0.0;
  A[221] = (A_tmp + d * 0.0) - d3;
}

/* End of code generation (makePredA_3D_Simple.c) */
