# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ipe/Imupos.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Imupos(genpy.Message):
  _md5sum = "b7b3c908ac554cd386d59718bc4de7e4"
  _type = "ipe/Imupos"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
float64[] b_acc_o
float64[] b_gyro
float64 mode
float64 kf_psi
float64 gyro_psi
float64[] cent_pos_est
float64[] cent_vel_est
float64 state_o
float64 acc_b_phi
float64 acc_b_theta
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','b_acc_o','b_gyro','mode','kf_psi','gyro_psi','cent_pos_est','cent_vel_est','state_o','acc_b_phi','acc_b_theta']
  _slot_types = ['std_msgs/Header','float64[]','float64[]','float64','float64','float64','float64[]','float64[]','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,b_acc_o,b_gyro,mode,kf_psi,gyro_psi,cent_pos_est,cent_vel_est,state_o,acc_b_phi,acc_b_theta

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Imupos, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.b_acc_o is None:
        self.b_acc_o = []
      if self.b_gyro is None:
        self.b_gyro = []
      if self.mode is None:
        self.mode = 0.
      if self.kf_psi is None:
        self.kf_psi = 0.
      if self.gyro_psi is None:
        self.gyro_psi = 0.
      if self.cent_pos_est is None:
        self.cent_pos_est = []
      if self.cent_vel_est is None:
        self.cent_vel_est = []
      if self.state_o is None:
        self.state_o = 0.
      if self.acc_b_phi is None:
        self.acc_b_phi = 0.
      if self.acc_b_theta is None:
        self.acc_b_theta = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.b_acc_o = []
      self.b_gyro = []
      self.mode = 0.
      self.kf_psi = 0.
      self.gyro_psi = 0.
      self.cent_pos_est = []
      self.cent_vel_est = []
      self.state_o = 0.
      self.acc_b_phi = 0.
      self.acc_b_theta = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.b_acc_o)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.b_acc_o))
      length = len(self.b_gyro)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.b_gyro))
      _x = self
      buff.write(_get_struct_3d().pack(_x.mode, _x.kf_psi, _x.gyro_psi))
      length = len(self.cent_pos_est)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.cent_pos_est))
      length = len(self.cent_vel_est)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.cent_vel_est))
      _x = self
      buff.write(_get_struct_3d().pack(_x.state_o, _x.acc_b_phi, _x.acc_b_theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.b_acc_o = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.b_gyro = s.unpack(str[start:end])
      _x = self
      start = end
      end += 24
      (_x.mode, _x.kf_psi, _x.gyro_psi,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.cent_pos_est = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.cent_vel_est = s.unpack(str[start:end])
      _x = self
      start = end
      end += 24
      (_x.state_o, _x.acc_b_phi, _x.acc_b_theta,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.b_acc_o)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.b_acc_o.tostring())
      length = len(self.b_gyro)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.b_gyro.tostring())
      _x = self
      buff.write(_get_struct_3d().pack(_x.mode, _x.kf_psi, _x.gyro_psi))
      length = len(self.cent_pos_est)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.cent_pos_est.tostring())
      length = len(self.cent_vel_est)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.cent_vel_est.tostring())
      _x = self
      buff.write(_get_struct_3d().pack(_x.state_o, _x.acc_b_phi, _x.acc_b_theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.b_acc_o = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.b_gyro = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 24
      (_x.mode, _x.kf_psi, _x.gyro_psi,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.cent_pos_est = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.cent_vel_est = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 24
      (_x.state_o, _x.acc_b_phi, _x.acc_b_theta,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
