function y = BPfilter(x)
%DOFILTER 입력값 x를 필터링하여 출력값 y를 반환합니다.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 18-Aug-2022 15:54:18

persistent Hd;

if isempty(Hd)
    
    Fstop1 = 1;    % First Stopband Frequency
    Fpass1 = 2;    % First Passband Frequency
    Fpass2 = 3;    % Second Passband Frequency
    Fstop2 = 5;   % Second Stopband Frequency
    Astop1 = 60;   % First Stopband Attenuation (dB)
    Apass  = 1;    % Passband Ripple (dB)
    Astop2 = 60;   % Second Stopband Attenuation (dB)
    Fs     = 100;  % Sampling Frequency
    
    h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
        Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

