// Generated by gencpp from file decawave_uwb/uwb_anchor.msg
// DO NOT EDIT!


#ifndef DECAWAVE_UWB_MESSAGE_UWB_ANCHOR_H
#define DECAWAVE_UWB_MESSAGE_UWB_ANCHOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace decawave_uwb
{
template <class ContainerAllocator>
struct uwb_anchor_
{
  typedef uwb_anchor_<ContainerAllocator> Type;

  uwb_anchor_()
    : header()
    , AnchorID()
    , ActiveNum(0)
    , Range()
    , Pos()  {
    }
  uwb_anchor_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , AnchorID(_alloc)
    , ActiveNum(0)
    , Range(_alloc)
    , Pos(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _AnchorID_type;
  _AnchorID_type AnchorID;

   typedef uint8_t _ActiveNum_type;
  _ActiveNum_type ActiveNum;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _Range_type;
  _Range_type Range;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _Pos_type;
  _Pos_type Pos;





  typedef boost::shared_ptr< ::decawave_uwb::uwb_anchor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decawave_uwb::uwb_anchor_<ContainerAllocator> const> ConstPtr;

}; // struct uwb_anchor_

typedef ::decawave_uwb::uwb_anchor_<std::allocator<void> > uwb_anchor;

typedef boost::shared_ptr< ::decawave_uwb::uwb_anchor > uwb_anchorPtr;
typedef boost::shared_ptr< ::decawave_uwb::uwb_anchor const> uwb_anchorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decawave_uwb::uwb_anchor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decawave_uwb::uwb_anchor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::decawave_uwb::uwb_anchor_<ContainerAllocator1> & lhs, const ::decawave_uwb::uwb_anchor_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.AnchorID == rhs.AnchorID &&
    lhs.ActiveNum == rhs.ActiveNum &&
    lhs.Range == rhs.Range &&
    lhs.Pos == rhs.Pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::decawave_uwb::uwb_anchor_<ContainerAllocator1> & lhs, const ::decawave_uwb::uwb_anchor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace decawave_uwb

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::decawave_uwb::uwb_anchor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decawave_uwb::uwb_anchor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decawave_uwb::uwb_anchor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decawave_uwb::uwb_anchor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decawave_uwb::uwb_anchor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decawave_uwb::uwb_anchor_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decawave_uwb::uwb_anchor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "817145bc463d481f2fcd524c9e839287";
  }

  static const char* value(const ::decawave_uwb::uwb_anchor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x817145bc463d481fULL;
  static const uint64_t static_value2 = 0x2fcd524c9e839287ULL;
};

template<class ContainerAllocator>
struct DataType< ::decawave_uwb::uwb_anchor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decawave_uwb/uwb_anchor";
  }

  static const char* value(const ::decawave_uwb::uwb_anchor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decawave_uwb::uwb_anchor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header \n"
"\n"
"uint32[] AnchorID\n"
"\n"
"uint8 ActiveNum\n"
"\n"
"float64[] Range\n"
"\n"
"geometry_msgs/Pose Pos\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::decawave_uwb::uwb_anchor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decawave_uwb::uwb_anchor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.AnchorID);
      stream.next(m.ActiveNum);
      stream.next(m.Range);
      stream.next(m.Pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct uwb_anchor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decawave_uwb::uwb_anchor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decawave_uwb::uwb_anchor_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "AnchorID[]" << std::endl;
    for (size_t i = 0; i < v.AnchorID.size(); ++i)
    {
      s << indent << "  AnchorID[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.AnchorID[i]);
    }
    s << indent << "ActiveNum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ActiveNum);
    s << indent << "Range[]" << std::endl;
    for (size_t i = 0; i < v.Range.size(); ++i)
    {
      s << indent << "  Range[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.Range[i]);
    }
    s << indent << "Pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.Pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECAWAVE_UWB_MESSAGE_UWB_ANCHOR_H
