
classdef uwb_anchor < ros.Message
    %uwb_anchor MATLAB implementation of decawave_uwb/uwb_anchor
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'decawave_uwb/uwb_anchor' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '817145bc463d481f2fcd524c9e839287' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Pos' 'AnchorID' 'ActiveNum' 'Range' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'Pos' 'AnchorID' 'ActiveNum' 'Range' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            'ros.msggen.geometry_msgs.Pose' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Pos
        AnchorID
        ActiveNum
        Range
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'uwb_anchor', 'Header')
            obj.Header = val;
        end
        function set.Pos(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'uwb_anchor', 'Pos')
            obj.Pos = val;
        end
        function set.AnchorID(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = uint32.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'uwb_anchor', 'AnchorID');
            obj.AnchorID = uint32(val);
        end
        function set.ActiveNum(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'uwb_anchor', 'ActiveNum');
            obj.ActiveNum = uint8(val);
        end
        function set.Range(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'uwb_anchor', 'Range');
            obj.Range = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.decawave_uwb.uwb_anchor.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.decawave_uwb.uwb_anchor(strObj);
        end
    end
end
