function y = LP_Filter(x)
%DOFILTER 입력값 x를 필터링하여 출력값 y를 반환합니다.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 05-Sep-2022 19:26:50

persistent Hd;

if isempty(Hd)
    
    Fpass = 0.01;   % Passband Frequency
    Fstop = 0.02;  % Stopband Frequency
    Apass = 1;     % Passband Ripple (dB)
    Astop = 60;    % Stopband Attenuation (dB)
    
    h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

